buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] || 'botsci' %>
  teams:
    editors: 3824115
    eics:
    reviewers:
  responders:
    help:
    hello:
      hidden: true
    thanks:
      hidden: true
    assign_editor:
      only: editors
    remove_editor:
      only: editors
      no_editor_text: "TBD"
    invite:
      only: editors
    add_remove_assignee:
      only: editors
    set_value:
      name: version
      only: editors
    label_command:
      command: review successful
      add_labels:
        - reviewed
        - pending publication
      remove_labels:
        - pending review
    welcome:
      message: "Hi!, I'm @botsci, a friendly bot.\n\nType ```@botsci help``` to discover how I can help you."
    ropensci_on_hold:
      only: editors
      on_hold_days: 30
