buffy:
  env:
    bot_github_user: 'botsci'
    gh_access_token: 'secret-access'
    gh_secret_token: 'secret-token'
    airtable_api_key: 'ropensci_airtable_api_key_abcde'
    airtable_base_id: 'ropensci_airtable_base_id_12345'
  teams:
    editors: 2009411
    eics:
    reviewers:
  responders:
    hello:
      only: editors
    thanks:
      hidden: true
